import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import TestComponent from '../components/TestComponent'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Schedule & Task Manager for a family</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        くさもちはうまい
      </div>
      <TestComponent></TestComponent>
    </>
  )
}
